version: '3.8'
services:
  bot:
    build: ./bot
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION_NAME
      - MODEL_ID
      - COMMUNITY_ID
      - LOBBY_ID
      - LLM_URL=http://llm:8000
    volumes:
      - ./logs:/app/logs
      - ./bot/.wwebjs_auth:/app/.wwebjs_auth
    depends_on:
      - llm
    restart: on-failure

  llm:
    build: ./llm
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION_NAME
      - MODEL_ID
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: on-failure
